---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  releaseName: authentik
  targetNamespace: authentik
  chart:
    spec:
      chart: authentik
      version: 2023.10.7
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
