---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  releaseName: authentik
  targetNamespace: authentik
  chart:
    spec:
      chart: authentik
      version: 2023.8.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
  interval: 5m # FIXME:
  maxHistory: 3
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  rollback:
    recreate: true
