---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: 3.2.7
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-values
      valuesKey: values.yaml
